// Mocks generated by Mockito 5.4.6 from annotations
// in yandex_school_finance/test/integration_test/edit_account_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:local_auth/src/local_auth.dart' as _i6;
import 'package:local_auth_android/local_auth_android.dart' as _i7;
import 'package:local_auth_darwin/local_auth_darwin.dart' as _i8;
import 'package:local_auth_windows/local_auth_windows.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:yandex_school_finance/data/datasources/drift/drift_database_datasource.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _Fake$TransactionTableTable_0 extends _i1.SmartFake
    implements _i2.$TransactionTableTable {
  _Fake$TransactionTableTable_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AccountTableTable_1 extends _i1.SmartFake
    implements _i2.$AccountTableTable {
  _Fake$AccountTableTable_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$CategoryTableTable_2 extends _i1.SmartFake
    implements _i2.$CategoryTableTable {
  _Fake$CategoryTableTable_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$BackupOperationTableTable_3 extends _i1.SmartFake
    implements _i2.$BackupOperationTableTable {
  _Fake$BackupOperationTableTable_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$DriftDatabaseDatasourceManager_4 extends _i1.SmartFake
    implements _i2.$DriftDatabaseDatasourceManager {
  _Fake$DriftDatabaseDatasourceManager_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_5 extends _i1.SmartFake
    implements _i3.GeneratedDatabase {
  _FakeGeneratedDatabase_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_6 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_7 extends _i1.SmartFake
    implements _i3.MigrationStrategy {
  _FakeMigrationStrategy_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_8 extends _i1.SmartFake
    implements _i3.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_9 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_10 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_11 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_12 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccountTableData_13 extends _i1.SmartFake
    implements _i2.AccountTableData {
  _FakeAccountTableData_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryTableData_14 extends _i1.SmartFake
    implements _i2.CategoryTableData {
  _FakeCategoryTableData_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionTableData_15 extends _i1.SmartFake
    implements _i2.TransactionTableData {
  _FakeTransactionTableData_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBackupOperationTableData_16 extends _i1.SmartFake
    implements _i2.BackupOperationTableData {
  _FakeBackupOperationTableData_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_17 extends _i1.SmartFake implements _i3.Migrator {
  _FakeMigrator_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_18<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_19<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_20<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_21<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_22<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_23<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_24<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_25<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_26 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalAuthentication extends _i1.Mock
    implements _i6.LocalAuthentication {
  MockLocalAuthentication() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get canCheckBiometrics =>
      (super.noSuchMethod(
            Invocation.getter(#canCheckBiometrics),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> authenticate({
    required String? localizedReason,
    Iterable<_i7.AuthMessages>? authMessages = const [
      _i8.IOSAuthMessages(),
      _i7.AndroidAuthMessages(),
      _i9.WindowsAuthMessages(),
    ],
    _i7.AuthenticationOptions? options = const _i7.AuthenticationOptions(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {
              #localizedReason: localizedReason,
              #authMessages: authMessages,
              #options: options,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> stopAuthentication() =>
      (super.noSuchMethod(
            Invocation.method(#stopAuthentication, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isDeviceSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isDeviceSupported, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i7.BiometricType>> getAvailableBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableBiometrics, []),
            returnValue: _i5.Future<List<_i7.BiometricType>>.value(
              <_i7.BiometricType>[],
            ),
          )
          as _i5.Future<List<_i7.BiometricType>>);
}

/// A class which mocks [DriftDatabaseDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriftDatabaseDatasource extends _i1.Mock
    implements _i2.DriftDatabaseDatasource {
  MockDriftDatabaseDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion =>
      (super.noSuchMethod(Invocation.getter(#schemaVersion), returnValue: 0)
          as int);

  @override
  _i2.$TransactionTableTable get transactionTable =>
      (super.noSuchMethod(
            Invocation.getter(#transactionTable),
            returnValue: _Fake$TransactionTableTable_0(
              this,
              Invocation.getter(#transactionTable),
            ),
          )
          as _i2.$TransactionTableTable);

  @override
  _i2.$AccountTableTable get accountTable =>
      (super.noSuchMethod(
            Invocation.getter(#accountTable),
            returnValue: _Fake$AccountTableTable_1(
              this,
              Invocation.getter(#accountTable),
            ),
          )
          as _i2.$AccountTableTable);

  @override
  _i2.$CategoryTableTable get categoryTable =>
      (super.noSuchMethod(
            Invocation.getter(#categoryTable),
            returnValue: _Fake$CategoryTableTable_2(
              this,
              Invocation.getter(#categoryTable),
            ),
          )
          as _i2.$CategoryTableTable);

  @override
  _i2.$BackupOperationTableTable get backupOperationTable =>
      (super.noSuchMethod(
            Invocation.getter(#backupOperationTable),
            returnValue: _Fake$BackupOperationTableTable_3(
              this,
              Invocation.getter(#backupOperationTable),
            ),
          )
          as _i2.$BackupOperationTableTable);

  @override
  _i2.$DriftDatabaseDatasourceManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$DriftDatabaseDatasourceManager_4(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i2.$DriftDatabaseDatasourceManager);

  @override
  Iterable<_i3.TableInfo<_i3.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i3.TableInfo<_i3.Table, Object?>>[],
          )
          as Iterable<_i3.TableInfo<_i3.Table, Object?>>);

  @override
  List<_i3.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i3.DatabaseSchemaEntity>[],
          )
          as List<_i3.DatabaseSchemaEntity>);

  @override
  _i3.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_5(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i3.GeneratedDatabase);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_6(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_7(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i3.MigrationStrategy);

  @override
  _i3.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_8(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i3.StreamQueryUpdateRules);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_9(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i10.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_10(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_11(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_12(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i5.Future<void> dropEverything() =>
      (super.noSuchMethod(
            Invocation.method(#dropEverything, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.AccountTableData>> getAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAccounts, []),
            returnValue: _i5.Future<List<_i2.AccountTableData>>.value(
              <_i2.AccountTableData>[],
            ),
          )
          as _i5.Future<List<_i2.AccountTableData>>);

  @override
  _i5.Future<_i2.AccountTableData> getAccountByLocalId(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountByLocalId, [id]),
            returnValue: _i5.Future<_i2.AccountTableData>.value(
              _FakeAccountTableData_13(
                this,
                Invocation.method(#getAccountByLocalId, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.AccountTableData>);

  @override
  _i5.Future<_i2.AccountTableData> updateAccountById(
    int? id,
    _i2.AccountTableCompanion? payload,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAccountById, [id, payload]),
            returnValue: _i5.Future<_i2.AccountTableData>.value(
              _FakeAccountTableData_13(
                this,
                Invocation.method(#updateAccountById, [id, payload]),
              ),
            ),
          )
          as _i5.Future<_i2.AccountTableData>);

  @override
  _i5.Future<List<_i2.CategoryTableData>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i5.Future<List<_i2.CategoryTableData>>.value(
              <_i2.CategoryTableData>[],
            ),
          )
          as _i5.Future<List<_i2.CategoryTableData>>);

  @override
  _i5.Future<_i2.CategoryTableData> getCategoryById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [id]),
            returnValue: _i5.Future<_i2.CategoryTableData>.value(
              _FakeCategoryTableData_14(
                this,
                Invocation.method(#getCategoryById, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.CategoryTableData>);

  @override
  _i5.Future<List<_i2.TransactionTableData>> getTransactionsInPeriod(
    int? accountId, [
    DateTime? startDate,
    DateTime? endDate,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsInPeriod, [
              accountId,
              startDate,
              endDate,
            ]),
            returnValue: _i5.Future<List<_i2.TransactionTableData>>.value(
              <_i2.TransactionTableData>[],
            ),
          )
          as _i5.Future<List<_i2.TransactionTableData>>);

  @override
  _i5.Future<List<_i2.TransactionTableData>> getTransactionsByAccount(
    int? accountId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByAccount, [accountId]),
            returnValue: _i5.Future<List<_i2.TransactionTableData>>.value(
              <_i2.TransactionTableData>[],
            ),
          )
          as _i5.Future<List<_i2.TransactionTableData>>);

  @override
  _i5.Future<_i2.TransactionTableData> createTransaction(
    _i2.TransactionTableCompanion? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [transaction]),
            returnValue: _i5.Future<_i2.TransactionTableData>.value(
              _FakeTransactionTableData_15(
                this,
                Invocation.method(#createTransaction, [transaction]),
              ),
            ),
          )
          as _i5.Future<_i2.TransactionTableData>);

  @override
  _i5.Future<_i2.TransactionTableData> updateTransactionByLocalId(
    int? id,
    _i2.TransactionTableCompanion? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransactionByLocalId, [id, transaction]),
            returnValue: _i5.Future<_i2.TransactionTableData>.value(
              _FakeTransactionTableData_15(
                this,
                Invocation.method(#updateTransactionByLocalId, [
                  id,
                  transaction,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.TransactionTableData>);

  @override
  _i5.Future<_i2.TransactionTableData> updateTransactionByRemoteId(
    int? id,
    _i2.TransactionTableCompanion? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransactionByRemoteId, [id, transaction]),
            returnValue: _i5.Future<_i2.TransactionTableData>.value(
              _FakeTransactionTableData_15(
                this,
                Invocation.method(#updateTransactionByRemoteId, [
                  id,
                  transaction,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.TransactionTableData>);

  @override
  _i5.Future<_i2.TransactionTableData> removeTransactionById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeTransactionById, [id]),
            returnValue: _i5.Future<_i2.TransactionTableData>.value(
              _FakeTransactionTableData_15(
                this,
                Invocation.method(#removeTransactionById, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.TransactionTableData>);

  @override
  _i5.Future<List<_i2.BackupOperationTableData>> getBackupOperations() =>
      (super.noSuchMethod(
            Invocation.method(#getBackupOperations, []),
            returnValue: _i5.Future<List<_i2.BackupOperationTableData>>.value(
              <_i2.BackupOperationTableData>[],
            ),
          )
          as _i5.Future<List<_i2.BackupOperationTableData>>);

  @override
  _i5.Future<_i2.BackupOperationTableData> createOrUpdateBackupOperation(
    _i2.BackupOperationTableCompanion? operation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createOrUpdateBackupOperation, [operation]),
            returnValue: _i5.Future<_i2.BackupOperationTableData>.value(
              _FakeBackupOperationTableData_16(
                this,
                Invocation.method(#createOrUpdateBackupOperation, [operation]),
              ),
            ),
          )
          as _i5.Future<_i2.BackupOperationTableData>);

  @override
  _i5.Future<void> removeBackupOperationById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeBackupOperationById, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i3.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_17(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i3.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i3.QueryExecutor? executor,
    _i3.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i5.Stream<T>.empty(),
          )
          as _i5.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i10.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i5.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i5.Stream<Set<_i3.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
    _i5.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i5.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_19<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_20<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_21<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_22<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_23<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_24<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i5.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
          )
          as _i5.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_25<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_25<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i5.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i10.ifNotNull(
                  _i10.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_18<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_26(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_26(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}
