// Mocks generated by Mockito 5.4.6 from annotations
// in yandex_school_finance/test/data/repositories/swagger_repositories/swagger_category_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yandex_school_finance/data/datasources/drift/drift_database_datasource.dart'
    as _i2;
import 'package:yandex_school_finance/data/models/freezed_models/account_models/account_model.dart'
    as _i3;
import 'package:yandex_school_finance/data/models/freezed_models/account_models/account_update_request_model.dart'
    as _i8;
import 'package:yandex_school_finance/data/models/freezed_models/category_model.dart'
    as _i10;
import 'package:yandex_school_finance/data/models/freezed_models/transaction_models/transaction_model.dart'
    as _i4;
import 'package:yandex_school_finance/data/models/freezed_models/transaction_models/transaction_request_model.dart'
    as _i9;
import 'package:yandex_school_finance/data/models/freezed_models/transaction_models/transaction_response_model.dart'
    as _i5;
import 'package:yandex_school_finance/data/repositories/swagger_repositories/swagger_drift_connection.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBackupOperationTableData_0 extends _i1.SmartFake
    implements _i2.BackupOperationTableData {
  _FakeBackupOperationTableData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccountModel_1 extends _i1.SmartFake implements _i3.AccountModel {
  _FakeAccountModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionModel_2 extends _i1.SmartFake
    implements _i4.TransactionModel {
  _FakeTransactionModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionResponseModel_3 extends _i1.SmartFake
    implements _i5.TransactionResponseModel {
  _FakeTransactionResponseModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionTableData_4 extends _i1.SmartFake
    implements _i2.TransactionTableData {
  _FakeTransactionTableData_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SwaggerDriftConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockSwaggerDriftConnection extends _i1.Mock
    implements _i6.SwaggerDriftConnection {
  MockSwaggerDriftConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> sync() =>
      (super.noSuchMethod(
            Invocation.method(#sync, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<dynamic> doEvent<T>(_i2.BackupOperationTableData? event) =>
      (super.noSuchMethod(
            Invocation.method(#doEvent, [event]),
            returnValue: _i7.Future<dynamic>.value(),
          )
          as _i7.Future<dynamic>);

  @override
  _i7.Future<_i2.BackupOperationTableData> addUpdateAccountByIdBackup(
    int? localId,
    int? remoteId,
    _i8.AccountUpdateRequestModel? updatedAccount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addUpdateAccountByIdBackup, [
              localId,
              remoteId,
              updatedAccount,
            ]),
            returnValue: _i7.Future<_i2.BackupOperationTableData>.value(
              _FakeBackupOperationTableData_0(
                this,
                Invocation.method(#addUpdateAccountByIdBackup, [
                  localId,
                  remoteId,
                  updatedAccount,
                ]),
              ),
            ),
          )
          as _i7.Future<_i2.BackupOperationTableData>);

  @override
  _i7.Future<_i2.BackupOperationTableData> addCreateTransactionBackup(
    int? localId,
    _i9.TransactionRequestModel? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addCreateTransactionBackup, [
              localId,
              transaction,
            ]),
            returnValue: _i7.Future<_i2.BackupOperationTableData>.value(
              _FakeBackupOperationTableData_0(
                this,
                Invocation.method(#addCreateTransactionBackup, [
                  localId,
                  transaction,
                ]),
              ),
            ),
          )
          as _i7.Future<_i2.BackupOperationTableData>);

  @override
  _i7.Future<_i2.BackupOperationTableData> addUpdateTransactionBackup(
    int? localId,
    int? remoteId,
    _i9.TransactionRequestModel? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addUpdateTransactionBackup, [
              localId,
              remoteId,
              transaction,
            ]),
            returnValue: _i7.Future<_i2.BackupOperationTableData>.value(
              _FakeBackupOperationTableData_0(
                this,
                Invocation.method(#addUpdateTransactionBackup, [
                  localId,
                  remoteId,
                  transaction,
                ]),
              ),
            ),
          )
          as _i7.Future<_i2.BackupOperationTableData>);

  @override
  _i7.Future<_i2.BackupOperationTableData> addDeleteTransactionBackup(
    int? localId,
    int? remoteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addDeleteTransactionBackup, [localId, remoteId]),
            returnValue: _i7.Future<_i2.BackupOperationTableData>.value(
              _FakeBackupOperationTableData_0(
                this,
                Invocation.method(#addDeleteTransactionBackup, [
                  localId,
                  remoteId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i2.BackupOperationTableData>);

  @override
  _i7.Future<List<_i3.AccountModel>> getAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAccounts, []),
            returnValue: _i7.Future<List<_i3.AccountModel>>.value(
              <_i3.AccountModel>[],
            ),
          )
          as _i7.Future<List<_i3.AccountModel>>);

  @override
  _i7.Future<_i3.AccountModel> getAccountById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAccountById, [id]),
            returnValue: _i7.Future<_i3.AccountModel>.value(
              _FakeAccountModel_1(
                this,
                Invocation.method(#getAccountById, [id]),
              ),
            ),
          )
          as _i7.Future<_i3.AccountModel>);

  @override
  _i7.Future<_i3.AccountModel> updateLocallyAccountById(
    int? id,
    _i8.AccountUpdateRequestModel? updatedAccount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocallyAccountById, [id, updatedAccount]),
            returnValue: _i7.Future<_i3.AccountModel>.value(
              _FakeAccountModel_1(
                this,
                Invocation.method(#updateLocallyAccountById, [
                  id,
                  updatedAccount,
                ]),
              ),
            ),
          )
          as _i7.Future<_i3.AccountModel>);

  @override
  _i7.Future<List<_i10.CategoryModel>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i7.Future<List<_i10.CategoryModel>>.value(
              <_i10.CategoryModel>[],
            ),
          )
          as _i7.Future<List<_i10.CategoryModel>>);

  @override
  _i7.Future<List<_i5.TransactionResponseModel>> getTransactionsInPeriod(
    int? accountId, [
    DateTime? startDate,
    DateTime? endDate,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsInPeriod, [
              accountId,
              startDate,
              endDate,
            ]),
            returnValue: _i7.Future<List<_i5.TransactionResponseModel>>.value(
              <_i5.TransactionResponseModel>[],
            ),
          )
          as _i7.Future<List<_i5.TransactionResponseModel>>);

  @override
  _i7.Future<_i4.TransactionModel> createLocallyTransaction(
    _i9.TransactionRequestModel? transaction, [
    int? remoteId,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#createLocallyTransaction, [
              transaction,
              remoteId,
            ]),
            returnValue: _i7.Future<_i4.TransactionModel>.value(
              _FakeTransactionModel_2(
                this,
                Invocation.method(#createLocallyTransaction, [
                  transaction,
                  remoteId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i4.TransactionModel>);

  @override
  _i7.Future<_i5.TransactionResponseModel> updateLocallyTransactionById(
    int? id,
    _i9.TransactionRequestModel? transaction, [
    bool? isRemoteId = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#updateLocallyTransactionById, [
              id,
              transaction,
              isRemoteId,
            ]),
            returnValue: _i7.Future<_i5.TransactionResponseModel>.value(
              _FakeTransactionResponseModel_3(
                this,
                Invocation.method(#updateLocallyTransactionById, [
                  id,
                  transaction,
                  isRemoteId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i5.TransactionResponseModel>);

  @override
  _i7.Future<_i2.TransactionTableData> removeLocallyTransactionById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeLocallyTransactionById, [id]),
            returnValue: _i7.Future<_i2.TransactionTableData>.value(
              _FakeTransactionTableData_4(
                this,
                Invocation.method(#removeLocallyTransactionById, [id]),
              ),
            ),
          )
          as _i7.Future<_i2.TransactionTableData>);
}
